# Generated by Django 4.1.2 on 2023-07-04 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_ad', '0004_remove_product_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='product',
        ),
    ]
