# Generated by Django 4.1.2 on 2023-07-04 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_ad', '0006_ad_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='category',
        ),
        migrations.AddField(
            model_name='ad',
            name='category',
            field=models.ManyToManyField(to='site_ad.category'),
        ),
    ]
