# Generated by Django 4.1.2 on 2023-07-05 18:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('site_ad', '0008_remove_ad_category_ad_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ad',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='seller',
        ),
        migrations.AddField(
            model_name='ad',
            name='added_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ad',
            name='photo',
            field=models.ImageField(blank=True, upload_to='ad_photos'),
        ),
    ]
