# Generated by Django 4.1.2 on 2023-07-16 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_ad', '0011_remove_ad_photo_large_remove_ad_photo_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='alias',
            field=models.SlugField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
