# Generated by Django 4.1.2 on 2023-07-16 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_ad', '0012_category_alias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='alias',
            field=models.SlugField(),
        ),
    ]
