# Generated by Django 4.1.2 on 2023-07-16 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_ad', '0013_alter_category_alias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='alias',
            field=models.CharField(max_length=25),
        ),
    ]
