# Generated by Django 4.1.2 on 2023-07-16 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_ad', '0014_alter_category_alias'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='seller',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, to='site_ad.user'),
            preserve_default=False,
        ),
    ]
