# Generated by Django 4.1.2 on 2023-07-18 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_ad', '0017_delete_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='email',
            field=models.EmailField(default='aaaa@mail.ru', max_length=254),
        ),
        migrations.AddField(
            model_name='ad',
            name='location',
            field=models.CharField(default='AAAA', max_length=100),
        ),
        migrations.AddField(
            model_name='ad',
            name='phone',
            field=models.CharField(default='+11111111', max_length=14),
        ),
    ]
